# Generated by Django 4.0.2 on 2022-02-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_verified_artist_print_verified_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
