# Generated by Django 4.0.2 on 2022-02-10 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_print_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main_app.print')),
            ],
        ),
    ]
