# Generated by Django 4.0.2 on 2022-02-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_giftset'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftset',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
