# Generated by Django 4.0.2 on 2022-02-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_giftset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftset',
            name='image',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
